### ISSUE TITLE
Error on Deno1.30.1

### ISSUE THREAD

**Issue by f1w3** [rayhanadev/crosis4furrets#5]
While I was using this library, I encountered a problem that I couldn't solve.
```js
const client = new Client({
    token: token,
    replId: replId
})
await client.connect()
```
The following error occurs when executing
```
not implemented: ClientRequest.setTimeout
error: Uncaught Error: Unexpected token 'P', "POST body "... is not valid JSON
    at new ApolloError (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:5582:28)
    at file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:7232:19
    at both (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:1702:53)
    at file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:1695:72
    at new Promise (<anonymous>)
    at Object.then (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:1695:24)  
    at Object.error (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:1703:49) 
    at notifySubscription (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:1119:18)
    at onNotify (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:1158:3)      
    at SubscriptionObserver.error (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:1211:5)
```
I understand that I shouldn't use deno, but I can't fix it myself (and I don't know the cause of the error), so I opened an issue

**Comment by rayhanadev** [comment]
How curious, while yes this library is built for Node.js and not Deno, the error doesn't seem to be with crosis4furrets itself, but a library it consumes (that I made) called `@rayhanadev/replit-gql` which is a wrapper around Apollo Client GraphQL but uses patched headers and node-fetch so it'll work on server.

I'm not quite sure what the error is there, it might be work looking into how `@apollo/client` and `node-fetch` behave in Deno. If I do come across a fix I will implement it!

**Comment by rayhanadev** [comment]
Presumably, this could be fixed by altering my GraphQL library and crosis4furrets into using their Web API equivalents because those are available in Deno... will see what I can do 😆.

**Comment by f1w3** [comment]
I have located where the problem is occurring.
In `@rayhanadev/replit-gql`, in `dist/index.mjs`, at line `2112:25`
```
{
  networkError: ServerParseError: Unexpected token 'P', "POST body "... is not valid JSON
    at JSON.parse (<anonymous>)
    at file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/@rayhanadev/replit-gql/1.2.1/dist/index.mjs:2112:25
    at Object.runMicrotasks (deno:core/01_core.js:397:30)
    at processTicksAndRejections (https://deno.land/std@0.176.0/node/_next_tick.ts:62:10)
}
```
seems to be the problem
If I check the variable `bodyText`
```
POST body missing, invalid Content-Type, or JSON object has no keys.
```
I found that the above error occurs because the above characters are stored and JSON.parse() is used to parse them.
